(set-logic DTLIA)
(synth-fun f ((x Int) (y Int)) (Tuple Int Int)
    ((T (Tuple Int Int)) (I Int))
    ((T (Tuple Int Int) ((mkTuple I I)))
      (I Int (x y (Constant Int)))))

(declare-var x Int)
(declare-var y Int)
(constraint (= ((_ tupSel 0) (f x 1)) x))
(constraint (= ((_ tupSel 1) (f 0 y)) 0))
(check-synth)